mamba_root: /root/autodl-tmp/.mamba
tools:
- tool_id: abricate
  env_name: autoplasm-annotation
  executable: abricate
- tool_id: amrfinderplus
  env_name: autoplasm-annotation
  executable: amrfinder
- tool_id: bakta
  env_name: autoplasm-annotation
  executable: bakta
- tool_id: blast
  env_name: autoplasm-annotation
  executable: blastn
- tool_id: bowtie2
  env_name: autoplasm-abundance
  executable: bowtie2
- tool_id: bowtie2_host_removal
  env_name: autoplasm-abundance
  executable: bowtie2
- tool_id: checkm2
  env_name: autoplasm-checkm2
  executable: checkm2
- tool_id: clinker
  env_name: autoplasm-visualization
  executable: clinker
- tool_id: concoct
  env_name: autoplasm-plasmid-binning
  executable: concoct
- tool_id: conjscan
  env_name: autoplasm-annotation
  executable: macsyfinder
- tool_id: copla
  env_name: autoplasm-annotation
  executable: copla
- tool_id: coverm
  env_name: autoplasm-abundance
  executable: coverm
- tool_id: das_tool
  env_name: stats
  executable: DAS_Tool
- tool_id: deseq2_plasmid
  env_name: stats
  executable: Rscript
- tool_id: dna_features_viewer
  env_name: autoplasm-visualization
  executable: python
- tool_id: dorado
  env_name: autoplasm-qc
  executable: dorado
- tool_id: eggnog_mapper
  env_name: autoplasm-annotation
  executable: emapper.py
- tool_id: fastp
  env_name: autoplasm-qc
  executable: fastp
- tool_id: fastqc
  env_name: autoplasm-qc
  executable: fastqc
- tool_id: fastspar
  env_name: stats
  executable: fastspar
- tool_id: filtlong
  env_name: autoplasm-qc
  executable: filtlong
- tool_id: genomad
  env_name: autoplasm-plasmid-detect
  executable: genomad
- tool_id: gplas2
  env_name: autoplasm-plasmid-binning
  executable: gplas2
- tool_id: gtdbtk
  env_name: stats
  executable: gtdbtk
- tool_id: hifiadapterfilt
  env_name: autoplasm-qc
  executable: hifiadapterfilt.sh
- tool_id: hifiasm_meta
  env_name: autoplasm-assembly
  executable: hifiasm
- tool_id: hybridspades
  env_name: autoplasm-assembly
  executable: spades.py
- tool_id: integronfinder
  env_name: autoplasm-integronfinder
  executable: integron_finder
- tool_id: isescan
  env_name: autoplasm-annotation
  executable: isescan.py
- tool_id: kraken2
  env_name: stats
  executable: kraken2
- tool_id: macsyfinder
  env_name: autoplasm-annotation
  executable: macsyfinder
- tool_id: medaka
  env_name: autoplasm-assembly
  executable: medaka_consensus
- tool_id: megahit
  env_name: autoplasm-assembly
  executable: megahit
- tool_id: metabat2
  env_name: autoplasm-plasmid-binning
  executable: metabat2
- tool_id: metaflye
  env_name: autoplasm-assembly
  executable: flye
- tool_id: metaphlan
  env_name: stats
  executable: metaphlan
- tool_id: metaspades
  env_name: autoplasm-assembly
  executable: metaspades.py
- tool_id: minced
  env_name: autoplasm-annotation
  executable: minced
- tool_id: minimap2
  env_name: autoplasm-abundance
  executable: minimap2
- tool_id: minimap2_host_removal
  env_name: autoplasm-abundance
  executable: minimap2
- tool_id: mmseqs2
  env_name: autoplasm-annotation
  executable: mmseqs
- tool_id: mob_suite
  env_name: autoplasm-annotation
  executable: mob_recon
- tool_id: mob_typer
  env_name: autoplasm-annotation
  executable: mob_typer
- tool_id: multiqc
  env_name: autoplasm-qc
  executable: multiqc
- tool_id: mummer
  env_name: autoplasm-plasmid-detect
  executable: nucmer
- tool_id: nanoplot
  env_name: autoplasm-qc
  executable: NanoPlot
- tool_id: opera_ms
  env_name: autoplasm-assembly
  executable: OPERA-MS.pl
- tool_id: plasmaag
  env_name: autoplasm-plasmid-binning
  executable: plasmaag
- tool_id: plasme
  env_name: autoplasm-plasmid-detect
  executable: python
- tool_id: plasmidfinder
  env_name: autoplasm-annotation
  executable: python
- tool_id: plasmidhostfinder
  env_name: autoplasm-annotation
  executable: plasmidhostfinder.py
- tool_id: plasx
  env_name: autoplasm-plasmid-detect
  executable: plasx
- tool_id: platon
  env_name: autoplasm-plasmid-detect
  executable: platon
- tool_id: prodigal
  env_name: autoplasm-annotation
  executable: prodigal
- tool_id: pycirclize
  env_name: autoplasm-visualization
  executable: python
- tool_id: pyvis
  env_name: autoplasm-visualization
  executable: python
- tool_id: quast
  env_name: autoplasm-assembly
  executable: metaquast.py
- tool_id: recycler
  env_name: autoplasm-plasmid-binning
  executable: python
- tool_id: report_markdown
  env_name: autoplasm-base
  executable: abi
- tool_id: rgi
  env_name: autoplasm-rgi
  executable: rgi
- tool_id: samtools
  env_name: autoplasm-abundance
  executable: samtools
- tool_id: samtools_fastq
  env_name: autoplasm-abundance
  executable: samtools
- tool_id: scapp
  env_name: autoplasm-scapp
  executable: scapp
- tool_id: semibin
  env_name: autoplasm-plasmid-binning
  executable: SemiBin2
