project_name: case3_ibd_easymetagenome_p1_pilot3_workers2
threads: 12
outdir: /root/autodl-tmp/abi-real-data/results/case3_ibd_p1_pilot3_retry_20260811
log_dir: /root/autodl-tmp/abi-real-data/logs/case3_ibd_p1_pilot3_retry_20260811

input:
  sample_sheet: /root/autodl-tmp/abi-real-data/configs/case3_ibd_p0_smoke_samples.tsv

resources:
  host_db: /root/autodl-tmp/resources/autoplasm/kneaddata_host
  humann_nucleotide_db: /root/autodl-tmp/resources/autoplasm/humann/chocophlan
  humann_protein_db: /root/autodl-tmp/resources/autoplasm/humann/uniref
  metaphlan_db: /root/autodl-tmp/resources/autoplasm/metaphlan

workflow:
  preset: p1_humann4

tool_params:
  fastp: {threads: 4}
  kneaddata: {threads: 4}

execution:
  parallel: true
  workers: 2
  error_policy: halt
  resume: true
  progress: true
