#!/usr/bin/env python3
"""Build the per-plugin ABI distributions (WP11B).

One repository, one version, one flow: every official plugin is packaged as
``abi-agent-plugin-<id>`` containing its implementation package
(``abi/plugins/<id>``) with co-located data (DAG, tool registry, limitations,
…).  The core ``abi-agent`` wheel stays plugin-free; discovery happens through
the ``abi.plugins`` entry points each plugin distribution declares.

与核心同版本、同流程：每个官方插件打包为 ``abi-agent-plugin-<id>``（实现包 +
同址数据 + 各自的入口点）；核心 wheel 不含插件。
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PLUGINS: dict[str, str] = {
    # plugin_id: entry-point class name (abi.plugins.<id>:<class>)
    "metagenomic_plasmid": "MetagenomicPlasmidPlugin",
    "metatranscriptomics": "MetatranscriptomicsPlugin",
    "rnaseq_expression": "RNASeqExpressionPlugin",
    "amplicon_16s": "Amplicon16SPlugin",
    "wgs_bacteria": "WGSBacteriaPlugin",
    "wgs_bacannot": "WGSBacannotPlugin",
    "easymetagenome": "EasyMetagenomePlugin",
    "viral_viwrap": "ViralViWrapPlugin",
}


def core_version() -> str:
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    try:
        import tomllib  # Python >= 3.11
    except ModuleNotFoundError:
        # The Docker build environment runs Python 3.10; fall back to a
        # narrow parse of the machine-formatted [project] version table.
        match = re.search(r'(?m)^version\s*=\s*"([^"]+)"\s*$', text)
        if match is None:
            raise SystemExit("core pyproject.toml has no project.version") from None
        return match.group(1)
    version = tomllib.loads(text)["project"]["version"]
    if not version:
        raise SystemExit("core pyproject.toml has no project.version")
    return str(version)


def stage_plugin(plugin_id: str, staging: Path) -> None:
    """Copy the implementation package (with co-located data) into staging."""

    code_root = ROOT / "src" / "abi" / "plugins" / plugin_id
    code_file = ROOT / "src" / "abi" / "plugins" / f"{plugin_id}.py"
    target = staging / "abi" / "plugins" / plugin_id

    if code_root.is_dir():
        shutil.copytree(code_root, target)
    elif code_file.is_file():
        target.mkdir(parents=True, exist_ok=True)
        shutil.copy2(code_file, target / f"{plugin_id}.py")
    else:
        raise SystemExit(f"plugin implementation not found for {plugin_id!r}")

    # Never ship bytecode caches from a dirty working tree.
    for cache in target.rglob("__pycache__"):
        shutil.rmtree(cache, ignore_errors=True)


def write_pyproject(staging: Path, plugin_id: str, class_name: str, version: str) -> None:
    dist_name = f"abi-agent-plugin-{plugin_id.replace('_', '-')}"
    (staging / "pyproject.toml").write_text(
        f"""
# Generated by scripts/build_plugin_wheels.py — do not edit.
[build-system]
requires = ["hatchling>=1.21,<1.32"]
build-backend = "hatchling.build"

[project]
name = "{dist_name}"
version = "{version}"
description = "ABI official plugin: {plugin_id} (code and co-located data)"
requires-python = ">=3.10"
dependencies = ["abi-agent=={version}"]

[project.entry-points."abi.plugins"]
{plugin_id} = "abi.plugins.{plugin_id}:{class_name}"

[tool.hatch.build.targets.wheel]
packages = ["abi"]

[tool.hatch.build.targets.sdist]
include = ["pyproject.toml", "abi"]
""",
        encoding="utf-8",
    )


def build_wheel(staging: Path, outdir: Path, *, no_build_isolation: bool = False) -> None:
    command = [
        sys.executable,
        "-m",
        "pip",
        "wheel",
        "--no-deps",
        "--no-cache-dir",
    ]
    if no_build_isolation:
        command.append("--no-build-isolation")
    command.extend(["-w", str(outdir), str(staging)])
    subprocess.run(command, check=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", default=str(ROOT / "dist"), help="Wheel output directory")
    parser.add_argument(
        "--plugin",
        action="append",
        choices=sorted(PLUGINS),
        help="Build only these plugins (repeatable; default: all).",
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="Also build the wheel for each staged distribution (default: stage only).",
    )
    parser.add_argument(
        "--no-build-isolation",
        action="store_true",
        help="Build wheels without pip build isolation (requires hatchling in the env).",
    )
    args = parser.parse_args()

    version = core_version()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    selected = args.plugin or sorted(PLUGINS)

    build_root = outdir / ".staging"
    shutil.rmtree(build_root, ignore_errors=True)
    build_root.mkdir(parents=True)

    staged: list[Path] = []
    for plugin_id in selected:
        staging = build_root / f"abi-agent-plugin-{plugin_id.replace('_', '-')}"
        stage_plugin(plugin_id, staging)
        write_pyproject(staging, plugin_id, PLUGINS[plugin_id], version)
        staged.append(staging)
        print(f"staged {plugin_id} -> {staging}")

    if args.build:
        for staging in staged:
            build_wheel(staging, outdir, no_build_isolation=args.no_build_isolation)
            print(f"built wheel {staging.name} -> {outdir}")

    if not args.build:
        print(f"version {version}; run `python -m build` in each staged directory")
    return 0


if __name__ == "__main__":
    sys.exit(main())
